// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPjiNC_lb7zVKH1oBZUDGUMeeZKdmU6SE',
    appId: '1:764211887191:web:f3555a371e1c62809fb712',
    messagingSenderId: '764211887191',
    projectId: 'whatsaapp-f87b3',
    authDomain: 'whatsaapp-f87b3.firebaseapp.com',
    storageBucket: 'whatsaapp-f87b3.appspot.com',
    measurementId: 'G-0CVLEC21M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6-nPM10vswdmxRq7IWCchB9TkUCEyenc',
    appId: '1:764211887191:android:d1f11a67343bd2c89fb712',
    messagingSenderId: '764211887191',
    projectId: 'whatsaapp-f87b3',
    storageBucket: 'whatsaapp-f87b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT58LHjeHtVuAWIPXFVeIgRO8FWK_zVDY',
    appId: '1:764211887191:ios:d0a586afaff241449fb712',
    messagingSenderId: '764211887191',
    projectId: 'whatsaapp-f87b3',
    storageBucket: 'whatsaapp-f87b3.appspot.com',
    iosBundleId: 'com.youssef.whatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT58LHjeHtVuAWIPXFVeIgRO8FWK_zVDY',
    appId: '1:764211887191:ios:c000b24b6fe316c79fb712',
    messagingSenderId: '764211887191',
    projectId: 'whatsaapp-f87b3',
    storageBucket: 'whatsaapp-f87b3.appspot.com',
    iosBundleId: 'com.youssef.whatsApp.RunnerTests',
  );
}
