name: whats_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
#  modal_progress_hud_nsn: ^0.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  bloc: ^8.1.2
  hexcolor: ^3.0.1
  status_view: ^0.0.2
  grouped_list: ^5.1.2
  flutter_bloc: ^8.1.3
  emoji_picker_flutter: ^1.6.3
  tab_indicator_styler: ^2.0.0
  permission_handler: ^10.2.0
  flutter_contacts: ^1.1.5+1
  flutter_slidable: ^3.0.1
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  iconsax: ^0.0.8
  timeago: ^3.3.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1

  firebase_core: ^2.20.0
  firebase_auth: ^4.12.1
  firebase_messaging: ^14.7.3
  firebase_storage: ^11.4.1
  cloud_firestore: ^4.12.2
  ionicons: ^0.2.2
  fluttercontactpicker: ^4.7.0
  shared_preferences: ^2.2.2
  audioplayers: ^5.1.0

  custom_clippers: ^1.0.0
#  provider: ^6.1.1
  cached_network_image: ^3.3.0
  file_picker: ^6.1.1
  story_view: ^0.15.0
  percent_indicator: ^4.2.3
  firebase_database: ^10.3.4
  swipe_to: ^1.0.4
  swipe_to_action: ^0.2.0
#  flutter_gif: ^0.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700